/// Motivational quotes for focus mode
library;

const List<String> motivationalQuotes = [
  'Focus is the gateway to success. You\'ve got this!',
  'Every moment of focus brings you closer to your goals.',
  'Your future self will thank you for focusing now.',
  'Distractions are temporary, but your goals are permanent.',
  'You are stronger than your distractions.',
  'Focus turns dreams into reality.',
  'This moment of focus will compound into greatness.',
  'Your goals are worth the sacrifice of distractions.',
  'Stay focused. Stay disciplined. Stay unstoppable.',
  'The only way out is through. Keep focusing.',
  'Pressure builds diamonds. Use this focus to shape yourself.',
  'Your attention is your most valuable asset. Protect it.',
  'One focused hour beats ten distracted hours.',
  'You\'ve already done the hard part—now just focus.',
  'This session will bring you closer to who you want to be.',
  'Discipline is choosing what you want most over what you want now.',
  'Your goals didn\'t get easier; you\'re just getting stronger.',
  'Focus creates momentum. Let\'s build it together.',
  'You are not alone in this journey. Stay focused.',
  'The pain of discipline is less than the pain of regret.',
  'Your potential is waiting. Focus and unlock it.',
  'Every second of focus is a step toward excellence.',
  'You\'ve overcome challenges before. This is temporary.',
  'Your mind is powerful when you give it direction through focus.',
  'This session is an investment in your future self.',
  'Stay committed to the process, trust the progress.',
  'The world needs what only you can create. Focus.',
  'You are capable of incredible things. Start now.',
  'Let your focus be your superpower.',
  'Remember why you started. Keep going.',
];
